Version of jquery-ui-min.js is changed.
The version of the jquery-ui-min is changed as the error 'Uncaught
TypeError: e.ui.isOverAxis is not a function' was coming in the console
on moving the widget in the Main Widget Area.